"""
Implementation of serializers cause json.loads() is not the django way :>
"""
from rest_framework import serializers


#We can change those serializers later to maybe provide proper types. But I guess frontend can handle that for now.
class DriverStandingSerializer(serializers.Serializer):
    """
    Serializer class for serializing the driver standings data.
    """
    position = serializers.IntegerField()
    positionText = serializers.CharField()
    points = serializers.FloatField()
    wins = serializers.IntegerField()
    driverId = serializers.CharField()
    driverNumber = serializers.IntegerField()
    driverCode = serializers.CharField()
    driverUrl = serializers.CharField()
    givenName = serializers.CharField()
    familyName = serializers.CharField()
    dateOfBirth = serializers.DateTimeField()
    driverNationality = serializers.CharField()
    constructorIds = serializers.ListField(child=serializers.CharField())
    constructorUrls = serializers.ListField(child=serializers.CharField())
    constructorNames = serializers.ListField(child=serializers.CharField())
    constructorNationalities = serializers.ListField(child=serializers.CharField())

class ConstructorStandingSerializer(serializers.Serializer):
    """
    Serializer class for serializing the constructor standings data.
    """
    position = serializers.CharField()
    positionText = serializers.CharField()
    points = serializers.CharField()
    wins = serializers.CharField()
    constructorId = serializers.CharField()
    constructorUrl = serializers.CharField()
    constructorName = serializers.CharField()
    constructorNationality = serializers.CharField()


class DriverCanWinSerializer(serializers.Serializer):
    """
    Serializer class for serializing the data generated by the who_can_still_win function.
    """
    position = serializers.CharField()
    driver_name = serializers.CharField()
    current_points = serializers.CharField()
    theoretical_max_points = serializers.CharField()
    can_win = serializers.CharField()
    gp_name = serializers.CharField()
