"""
Implementation of serializers cause json.loads() is not the django way :>
"""
from rest_framework import serializers

class DriverCanWinSerializer(serializers.Serializer):
    """
    Serializer class for serializing the data generated by the who_can_still_win function.
    """
    position = serializers.CharField()
    driver_name = serializers.CharField()
    current_points = serializers.CharField()
    theoretical_max_points = serializers.CharField()
    can_win = serializers.CharField()
    gp_name = serializers.CharField()
